### ISSUE TITLE
Dengue in Pakistan in 2021 and 2022 seems to be wildly undercounted

### ISSUE THREAD

**Issue by jnickla1** [OpenDengue/master-repo#13]
Hello - apologies if this should be categorized as a data source rather than a bug.

This first published source https://pmc.ncbi.nlm.nih.gov/articles/PMC7256837/ broadly agrees with the numbers reported for the 2017 outbreak in Pakistan ~25000, although it also included yearly numbers by province and December cases:  

This second published source https://www.sciencedirect.com/science/article/pii/S2773049223000326 reports total case numbers of "3442 cases in 2020. In 2021, there were 48 906 confirmed cases. There have been 41 746 confirmed cases of dengue in Pakistan as of October 11, 2022". This wildly disagrees with your reported numbers of 1933, 1220, and 482 for the years 2020, 2021, and 2022 respectively. 

Additionally, I think that weekly case reports by province are available here in the IDSR bulletins https://www.nih.org.pk/phb/weekly-bulletin from 2021 through 2024, and could be added to the dataset.

**Comment by ahyoung-lim** [comment]
Thank you for bringing these sources to our attention and for your detailed input.

We’ve reviewed the first publication you provided, and we’ve now added this source to our list for inclusion in the next update.

Regarding the second publication, the figures cited lack sufficient information on their origin (e.g., a direct link to reports or bulletins from the National Institute of Health). As a result, we will categorise this as literature, which, under our data processing protocol, is given the lowest priority for inclusion. 

We are happy to share that the third source (IDSR bulletins from NIH Pakistan) has already been included in our dataset available from the latest release. 👍

Thank you again for your valuable feedback and contributions to improving the dataset!
