### ISSUE TITLE
Bhutan Dengue Case Data 2019, 2020

### ISSUE THREAD

**Issue by beoutbreakprepared** [OpenDengue/master-repo#5]
Collated some Bhutanese case data from MoH resources
Please see attached file, with provenance of resources associated
2019 resources are broken down by administrative unit
[bhutan_2019_2020.csv](https://github.com/OpenDengue/master-repo/files/11725133/bhutan_2019_2020.csv)

**Comment by ahyoung-lim** [comment]
Thank you very much for your contribution. We will carefully review the data sources you've suggested and work on integrating them into our datasets. We will keep you updated on the progress and notify you when the changes are implemented.
