### ISSUE TITLE
Italy data 2018-2022

### ISSUE THREAD

**Issue by gorkang** [OpenDengue/master-repo#8]
**Describe the data sources**
The Istituto Superiore di Sanità has a website collecting Italy data from 2018 to 2022: https://www.epicentro.iss.it/arbovirosi/bollettini

**Additional context**
The yearly pdf's show the historical monthly trend stating in 2015.

**Comment by gorkang** [comment]
Or even better. You can access all European data 2008-2021:

https://atlas.ecdc.europa.eu/public/index.aspx

**Comment by ahyoung-lim** [comment]
Thanks for finding this! Both data will be carefully reviewed and included in our upcoming updates 👍
