### ISSUE TITLE
Official Open Data for Peru: 2000 - 2022

### ISSUE THREAD

**Issue by jmcastagnetto** [OpenDengue/master-repo#9]
**Official Open Data**

The Dir. of Epidemiology (DGE, aka, CDC Perú) of the Ministry of Health of Perú (MINSA), has published Open  Data at the individual case level, including three diagnostic types: Dengue without alarm signals, with alarm signals, and grave. The published data also includes year, epi week, age, sex and location at the District level (ADM3) and in some cases, up to locality (ADM4, 80% of rows). Peru has the following organization: Departamento (ADM1) > Provincia (ADM2) > District (ADM3) > Localidad/Centro Poblado (ADM4)

The URL for the dataset is: https://www.datosabiertos.gob.pe/dataset/vigilancia-epidemiol%C3%B3gica-de-dengue, where you can get the CSV format directly or programmatically using the API for DKAN (which is what the national Open Data platform uses).

At that URL, there is also documentation of the data dictionary of that dataset.

Let me know if you got some questions on that dataset and I can try to help.

**Comment by ahyoung-lim** [comment]
Thank you for your contribution! Our upcoming update will definitely include it 👍 
Just wanted to ask if there are any data from 2023 onwards available on the platform? - I tried a quick search without success so any advice would be really helpful.

**Comment by jmcastagnetto** [comment]
@ahyoung-lim, AFAIK they are planning on publishing annual datasets, will reach out to the people I think are processing the data at the Min. of Health in Peru, and let you know what I learn.

**Comment by jmcastagnetto** [comment]
@ahyoung-lim OK, got a response from the people from CDC Peru, they say that the data should be ready by the end of May approx., after that it will be published in the National Open Data platform.

**Comment by ahyoung-lim** [comment]
@jmcastagnetto Thanks so much! Really helpful. Will keep an eye out for the data update and include it together 👍

**Comment by LaughingKing1** [comment]
@jmcastagnetto I was wondering if there was any updates on the release for the 2023-2024 data?

**Comment by jmcastagnetto** [comment]
Hi @LaughingKing1, just asked the people at DGE (CDC Perú), and one of them told me that they should be finishing the cleanup and review this week, and publish the data afterwards. Hit me again later this month in case the update is not up yet.

**Comment by LaughingKing1** [comment]
Hi @jmcastagnetto, thanks for checking I really appreciate the update!
